### ISSUE TITLE
Using the F95 Survey Sim for publication in PyPI

### ISSUE THREAD

**Issue by jmpetit** [OSSOS/SurveySimulator#6]
As Sam and JJ said, the discussion that I've started on porting the SSim to PyPI and using the F95 routines rather than the F77 ones should not be part of the pull request from Lowell. So I start this "issue" thread. I'll copy the relevant part from the pull request to set the context. I'll give my new thoughts in the next comment.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
jmpetit, Fri, 13 Mar 2020

Hi there,

I just became aware of this project very recently. I didn't know you wanted to create a pipy distribution of the survey simulator. That sounds like a good idea. Does this mean you'll have to rewrite the whole thing in Python, or can you keep the survey simulator itself in Fortran (there exist a F95 version which is now the active one) and only rewrite the driver and GiMeObj ?

For GiMeObj, this is supposed to be supplied by the user, and depends heavily on the model one wants to implement. The only generic version is ReadModelFromFile.f95.

If going for a large distribution the survey simulator, I guess we should try and parallelize the the core of the program, the Detos1 routine. We can do this in the driver which would launch multiple instances of Detos1, likely with multiple MPI threads, or using somethink like the multiprocessing module from python. In this case, we need to feed each instance of Detos1 with many objects so it spends some time churning the number before being caught in the administration overhead. An other way to parallelize is to feed Detos1 with many objects at once, and then make it run in parallel with some OpenMP mechanism or other multithreading inside Detos1. Whether one should paralellize with respect to objects or surveys remains to be seen.

I've seen there are 2 issues open. I'll give some info on each of them directly in the individual threads.

Cheers, Jean-Marc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ijiraq, Fri, 13 Mar 2020

Going with pyPI does not require moving to python only code.  We have
fortran code that is part of the pyPI distribution and compile that during
install. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cshankm, Fri, 13 Mar 2020

I'm happy to see the Python wrapper/implementation of the survey
simulator live on! The python wrapper and tools I was using were definitely
slower in the runtime testing I did, but the flexibility and ease of
configuring different models to test in python more than made up for that
for me. 
Cory

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
LowellPeltier, Fri, 13 Mar 2020

It is my understanding that trying to run the entire survey simulator using
python is much too slow to be of use. However, I'm not sure how much effort
has been expended investigating this in the past. Python generally has a
reputation for being pretty slow. 

As for the PyPI package, It shouldn't be a problem to have the core files
written in fortran. Rebound for example is a Package that runs using C code
and is available through PIP. In our specific case with fortran I'm not sure
of exactly what will be required to accomplish this, but I don;t see a
reason why it can't be done. As it stands how we will compile and use the
fortran is a question I don't have a good answer to. The .so files created
by F2PY are not portable between systems as far as I'm aware, but this is
well outside my bailiwick my background is physics not computer science.
Worst case scenario rather than providing something already compiled that
can be used immediately, we provide the source files and instructions or
some code to compile the fortran on the user's system.

Currently this python code is operating off of an older F77 implementation
of the survey simulator. I saw the updates made to the source code in the
repository, but I wasn't able to get them to compile using F2PY. Instead Sam
provided me with the working version she had been using. Looking at the F2PY
documentation I remember there being some idiosyncrasies compiling F95
files, perhaps that's what the problem was. 

You are correct that GiMeObj is intended to be created by the user, but the
python module supplied here is more of a template for how that would be
accomplished. By implementing a class structure for object populations this
allows a lot of versatility and modularity in designing a GiMeObj file.
However this structure is somewhat different to the usual procedural
programming done by many scientists. It's certainly possible for users to
design their own version completely from scratch, but I'm hoping this can
reduce the learning curve, allowing them to skip most of the computer
science and jump right into survey simulation.

As for parallelization, it's not something I have experience with but I can
do some research on it. I believe it could be accomplished either through
the python Driver, or within the fortran itself. Both would be viable, but
other's experience may inform which is the better approach.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cshankm, Fri, 13 Mar

I haven't looked at or kept up with this stuff in years, so I
don't know the current state of the survey simulator or anything like that.
But what I was doing a few years ago, which I think is what you're building
off of Lowell is:Compiling f2py on my machine and/or virtual machine for
cluster deployment. I provided instructions for how others could do that if
they wanted to use the python wrapper. And I only used the most basic
paralellization where you run independent jobs on different clusters and
assemble later. Stupidly simple paralellization, but it gets the job done.
Won't take advantage of GPU clusters or similar though. And I haven't seen
your updates to the python gimiobj, but that's exactly the approach I was
taking as well. Providing. A set of tools to sample Hmag, inclination and
other distributions. I didn't get as far as building tools to model
resonance or other populations, but I think that's definitely the next
step. For the simulations I was running, I found the cluster approach to be
fast enough. Though maybe some of the populations you folks are modelling
now are more computationally intensive. Cory

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
samlawler, Fri, 13 Mar 2020

Hi everyone!

Let me just re-iterate that what we've tried to do here (and by "we," I mean
Lowell since he did all the work) is make a version of the Survey Simulator
that is easy for someone outside OSSOS to download and work.  What we're
hoping to get from all of you experts taking a look at the improved version
is:
1) Anything that we've missed in the python wrapper or anything that needs
to be explained better to a non-OSSOS person
2) Help and suggestions for getting the fortran core of the code to work on
multiple different systems - we've only been able to test it with Ubuntu
because that's what we have.

If anyone thinks this discussion would be better served with a telecon, let
me know and I'll set one up for the next couple of weeks.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ijiraq, Fri, 13 Mar 2020

I also don't want to stifle this great interaction that has started.  But
suggest that the pull request thread is the wrong place for this.  A
standard issue would be a better place.   Otherwise it will be impossible
for Lowell to get his requested changes accepted.  So, in this thread,
please only review the code and post code review comments. 

BTW:  'where are the tests' is a totally valid question at the code review
level. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by jmpetit** [comment]
Hi there,

now are some thoughts on this issue.

I've looked in more details into how F2PY works. Because it was first developed for F77, it has limitations, such as not handling variable dimention output data and use of derived types. I've been transcoding several F77 programs to F95 and had no problem to run them through F2PY because I was just doing a transcription, with no strucutral change. In the Survey Simulator, I developped the F95 routines because I wanted to avoid the large number of argument when calling the routines. I wanted to have the variables and arguments grouped by meaning or functionality. Hence I designed several derived types, some simple (vectors, orbital elements), some more complex (efficiency, pointings). And I use them in other programs that require the survey sim.

The solutions for using the F95 survey sim are:
- revert to using standard types, like arrays; this would mean a huge work of re-writing all the subroutine;
- create a Fortran wrapper that has only simple types like array as input and output but call the other F95 routines with derived types; that's assuming F2PY would accept to compile that as long as there is no derived type in the API; this means much copying of data, so an extra slow-down
- give up the F95 survey sim for this project; this means I'll have to maintain both F77 and F95 routines in the main branch;
- try to use Ctypes or Cython to manually write the interface between the F95 shared library and the python program; I've seen posts on the web that seem to indicate this is the right way to go.

I guess I'm going to try the last approach. Any of you acquainted with either solution ?

Cheers, Jean-Marc

**Comment by jmpetit** [comment]
Hi there,

I've made much progress on using F95 or more modern Fortran to write modules for Python. I came accros the nice program f90wrap (available on PyPi with pip) which allows to use derived types in Fortran and produce Python modules. I have revamped my Fortran95 code to be compatible with this tool. All the sources for the survey simulator in F95 are in srcF95. There are examples of using it directly in Fortran in lookupF95 and parametricF95, and as module for Python in lookupPF95 and parametricPF95.

I know this is somewhat orthogonal to your current Python development, but remember that in the future, I maybe dropping the F77 support. Also I see a cost in compute time of more than 10% when going from pure Fortran to Python calling 2 Fortran functions. Here, the Python overhead is really just getting data from Gimeobj and feeding it into detos1. I guess I could regain part of these 10% by creating a new routine that calls Gimeobj and detos1 sequentially and return only when it finds an object that is detected and tracked.

I'd be interested to see how fast can you Python code for Gimeobj be.

Cheers, JM

**Comment by ijiraq** [comment]
Python code has now migrated to a more pythonic module approach.
