### ISSUE TITLE
'Quick Start' folder pathway incorrect in SurveySimulator/README.md

### ISSUE THREAD

**Issue by rcdorsey** [OSSOS/SurveySimulator#9]
Readme file currently says:

"Quick Start
Look in parametric/exmaple/README.parametric for an example of how run Simulator."

parametric folder no longer exists, so I believe the correct pathing is now:

"Quick Start
Look in python/README_parametric.txt for an example of how to run the Simulator."

**Comment by ijiraq** [comment]
Thanks.  We have been moving around the file structure to try and clarify the usage a bit but have not updated all the README files.   Resolved.
